Vagrant.configure("2") do |config|
  
 		config.ssh.username='vagrant'
 		config.ssh.password='vagrant'
 		config.vm.box = "bertvv/centos72"
  		config.vm.provider "virtualbox" do |vb|
     end
  
config.vm.provision "shell", path: "utils.sh"
 
	config.vm.define "server" do |server|
  	server.vm.hostname = "server"
  	server.vm.network "private_network", ip: "10.0.0.10"
  	server.vm.provision "shell", path: "server.sh"
  end

	config.vm.define "client" do |client|
  	client.vm.hostname = "client"
  	client.vm.network "private_network", ip: "10.0.0.11"
  	client.vm.provision "shell", privileged: false, path: "client.sh"
  end


end