Vagrant.configure("2") do |config|
  
 		config.ssh.username='vagrant'
 		config.ssh.password='vagrant'
 		config.vm.network "forwarded_port", guest: 80, host: 81
  		config.vm.box = "bertvv/centos72"
  		config.vm.provider "virtualbox" do |vb|
     end
  
  config.vm.provision "shell", path: "utils.sh"
  config.vm.provision "shell", path: "tomcat.sh"
  config.vm.provision "shell", path: "apache.sh"
  
  
end

	